In [1]:
import numpy as np
import pandas as pd
TagAlongCodes_data = pd.read_csv ("FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding = "latin - 1")

In [13]:
'FIRST_count'= TagAlongCodes_data.groupby('Y2014').agg({'item' : 'sum'})

SyntaxError: cannot assign to literal (692394427.py, line 1)

In [14]:
TagAlongCodes_data.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [15]:
TagAlongCodes_data.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [16]:
TagAlongCodes_data.corr()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area Code,1.000000,-0.005159,-0.000209,0.006164,0.005472,0.005247,0.005006,0.005665
Item Code,-0.005159,1.000000,-0.024683,0.021722,0.020857,0.020109,0.021494,0.021314
Element Code,-0.000209,-0.024683,1.000000,0.024457,0.023889,0.023444,0.024254,0.024279
Y2014,0.006164,0.021722,0.024457,1.000000,0.994647,0.996081,0.995230,0.994872
Y2015,0.005472,0.020857,0.023889,0.994647,1.000000,0.995739,0.988048,0.988208
Y2016,0.005247,0.020109,0.023444,0.996081,0.995739,1.000000,0.992785,0.992757
Y2017,0.005006,0.021494,0.024254,0.995230,0.988048,0.992785,1.000000,0.998103
Y2018,0.005665,0.021314,0.024279,0.994872,0.988208,0.992757,0.998103,1.000000

In [17]:
import_quality = TagAlongCodes_data.groupby('Element').sum()

In [18]:
print (import_quality)

                                        Area Code  Item Code  Element Code  \
Element
Domestic supply quantity                   708993   14197445      28068795
Export Quantity                            599910   11840553      26026133
Fat supply quantity (g/capita/day)         675050   13535000       3435732
Feed                                       176272    3538507       7282199
Food                                       663295   13285035      25406622
Food supply (kcal/capita/day)              674057   13511060       3329296
Food supply quantity (kg/capita/yr)        658446   13185401       3163725
Import Quantity                            688174   13795966      28834929
Losses                                     274353    5424803      10292107
Other uses (non-food)                      235554    4729749       8926728
Processing                                 271940    5350416      10313310
Production                                 526751   10450053      21388191
Protein supply quantity (g/capita/day)     675050   13535000       3385502
Residuals                                  623271   12421089      24066350
Seed                                       103537    2035933       4211574
Stock Variation                            571566   11329527      21464704
Total Population - Both sexes                6020     112545         22995
Tourist consumption                         50308    1486528       2869905

                                             Y2014       Y2015       Y2016  \
Element
Domestic supply quantity                1996716.35  2021493.55  2044842.70
Export Quantity                          150020.64   157614.47   151920.46
Fat supply quantity (g/capita/day)        10225.56    10235.74    10102.77
Feed                                     216927.89   225050.22   228958.65
Food                                    1212332.49  1232361.10  1247022.17
Food supply (kcal/capita/day)            454257.00   453383.00   451810.00
Food supply quantity (kg/capita/yr)       49650.63    49345.13    48985.28
Import Quantity                          274144.48   267018.46   286582.78
Losses                                   153223.00   155439.00   157787.00
Other uses (non-food)                     78718.13    66254.41    69563.68
Processing                               282923.00   287929.00   280631.00
Production                              1931287.75  1947019.39  1943537.15
Protein supply quantity (g/capita/day)    11836.46    11833.95    11779.69
Residuals                                 30149.00    30045.00    37224.00
Seed                                      21922.92    23976.82    23389.20
Stock Variation                           58749.83    34910.99    33140.12
Total Population - Both sexes           1031585.00  1058081.00  1085107.00
Tourist consumption                         416.00      349.00       89.00

                                             Y2017       Y2018
Element
Domestic supply quantity                2088198.10  2161192.10
Export Quantity                          182338.80   181594.80
Fat supply quantity (g/capita/day)        10253.84    10258.69
Feed                                     223705.68   233489.68
Food                                    1258888.28  1303841.28
Food supply (kcal/capita/day)            454681.00   455261.00
Food supply quantity (kg/capita/yr)       48690.04    49056.85
Import Quantity                          294559.09   287997.09
Losses                                   160614.00   163902.00
Other uses (non-food)                     91645.97    91300.97
Processing                               292836.00   308429.00
Production                              2030056.89  2075072.89
Protein supply quantity (g/capita/day)    11842.45    11833.56
Residuals                                 35500.00    34864.00
Seed                                      24870.14    25263.14
Stock Variation                           54316.91    20577.91
Total Population - Both sexes           1112641.00  1140605.00
Tourist consumption                          91.00       90.00

In [21]:
Animal_fatCount = TagAlongCodes_data.groupby('Item').sum()

In [22]:
print (Animal_fatCount)

                     Area Code  Item Code  Element Code      Y2014      Y2015  \
Item
Alcohol, Non-Food        38447     752497       1515090    2403.00    2180.00
Alcoholic Beverages      75016    1649136       2171381  102410.11   98783.72
Animal Products          18060     397035         90990   11935.65   11811.73
Animal fats              85279    1882494       2567303  209460.54  200675.72
Apples and products      69280    1352989       1920418    9499.23   10559.15
...                        ...        ...           ...        ...        ...
Vegetables, Other        77779    1518715       2275409  155038.96  158104.08
Vegetal Products         18060     391905         90990  107145.19  107064.17
Wheat and products       87073    1639683       2654934  232670.13  234710.51
Wine                     66206    1319535       1818328    4497.36    4251.81
Yams                     50798     970905       1525745  200396.96  203151.78

                         Y2016      Y2017      Y2018
Item
Alcohol, Non-Food      2223.00    2348.00    2293.00
Alcoholic Beverages   96958.75   95581.06   97847.27
Animal Products       11661.69   11547.65   11578.61
Animal fats          183314.22  269617.53  269648.27
Apples and products    9853.26   10198.90    9640.51
...                        ...        ...        ...
Vegetables, Other    156218.90  157752.59  163987.21
Vegetal Products     106792.72  107655.20  107775.39
Wheat and products   239377.07  240047.62  242645.19
Wine                   3872.09    4178.02    4039.32
Yams                 220626.20  229174.59  221272.09

[119 rows x 8 columns]

In [25]:
print (TagAlongCodes_data.head(12))

    Area Code     Area  Item Code                      Item  Element Code  \
0           4  Algeria       2501                Population           511
1           4  Algeria       2501                Population          5301
2           4  Algeria       2901               Grand Total           664
3           4  Algeria       2901               Grand Total           674
4           4  Algeria       2901               Grand Total           684
5           4  Algeria       2903          Vegetal Products           664
6           4  Algeria       2903          Vegetal Products           674
7           4  Algeria       2903          Vegetal Products           684
8           4  Algeria       2941           Animal Products           664
9           4  Algeria       2941           Animal Products           674
10          4  Algeria       2941           Animal Products           684
11          4  Algeria       2905  Cereals - Excluding Beer          5511

                                   Element             Unit     Y2014  \
0            Total Population - Both sexes     1000 persons  38924.00
1                 Domestic supply quantity      1000 tonnes      0.00
2            Food supply (kcal/capita/day)  kcal/capita/day   3377.00
3   Protein supply quantity (g/capita/day)     g/capita/day     94.90
4       Fat supply quantity (g/capita/day)     g/capita/day     80.06
5            Food supply (kcal/capita/day)  kcal/capita/day   2932.00
6   Protein supply quantity (g/capita/day)     g/capita/day     67.14
7       Fat supply quantity (g/capita/day)     g/capita/day     53.84
8            Food supply (kcal/capita/day)  kcal/capita/day    444.00
9   Protein supply quantity (g/capita/day)     g/capita/day     27.76
10      Fat supply quantity (g/capita/day)     g/capita/day     26.22
11                              Production      1000 tonnes   3436.00

       Y2015     Y2016     Y2017     Y2018
0   39728.00  40551.00  41389.00  42228.00
1       0.00      0.00      0.00      0.00
2    3379.00   3372.00   3341.00   3322.00
3      94.35     94.72     92.82     91.83
4      79.36     77.40     80.19     77.28
5    2958.00   2941.00   2921.00   2932.00
6      67.38     67.37     66.11     67.10
7      54.72     52.04     55.59     54.57
8     421.00    431.00    421.00    390.00
9      26.97     27.35     26.71     24.73
10     24.64     25.37     24.60     22.71
11   3761.00   3445.00   3478.00   6065.00

In [34]:
algeriaSum = TagAlongCodes_data.groupby('Area').agg({'Y2018' : 'sum', 'Import Quantity'[] : 'sum'})

NameError: name 'Y2018' is not defined

In [32]:
print (algeriaSum)

                                  Y2018
Area
Algeria                       341729.98
Angola                        235206.68
Benin                         124960.70
Botswana                       23129.08
Burkina Faso                  112970.72
Cabo Verde                     14622.60
Cameroon                      233022.93
Central African Republic       30101.57
Chad                           72282.24
Comoros                           59.84
Congo                          42005.53
Côte d'Ivoire                 227018.00
Djibouti                       23718.96
Egypt                         852652.92
Eswatini                       55045.07
Ethiopia                      450788.86
Ethiopia PDR                       0.00
Gabon                          28339.38
Gambia                         23513.80
Ghana                         358915.64
Guinea                        103262.08
Guinea-Bissau                  18997.92
Kenya                         270916.80
Lesotho                        19109.23
Liberia                        29629.83
Madagascar                    134576.44
Malawi                        187366.09
Mali                          159026.42
Mauritania                    157479.95
Mauritius                      47150.91
Morocco                       399271.27
Mozambique                    164934.05
Namibia                        29350.04
Niger                         133982.86
Nigeria                      1499774.24
Rwanda                         74839.08
Sao Tome and Principe          12806.49
Senegal                        95493.82
Seychelles                       442.34
Sierra Leone                   55981.73
South Africa                  509787.97
Sudan                         268054.39
Sudan (former)                     0.00
Togo                           54872.00
Tunisia                       127343.17
Uganda                        222147.25
United Republic of Tanzania   349763.41
Zambia                        101604.27
Zimbabwe                       76581.41

In [35]:
TagAlongCodes_data.loc['Y2018', 'Imported Quantity'].sum()

KeyError: 'Imported Quantity'